# Navigation Links
# The site logo links to the homepage, so Home is intentionally omitted.

main:
  - name: Research
    url: /projects/
    weight: 10

  - name: People
    url: /people/
    weight: 20

  - name: Media
    identifier: media
    weight: 30

  - name: News
    url: /post/
    parent: media
    weight: 1

  - name: Photo Gallery
    url: /media/
    parent: media
    weight: 2

  - name: Funding
    url: /funding/
    parent: media
    weight: 3

  - name: Outreach
    identifier: outreach
    weight: 40

  - name: Opportunities
    url: /opportunities/
    parent: outreach
    weight: 1

  - name: BhamXR
    url: https://www.birmingham.ac.uk/research/centres-institutes/bhamxr
    parent: outreach
    weight: 2

  - name: Blog
    url: /blog/
    weight: 50

  - name: Events
    url: /event/
    weight: 60

  # Internal sections for VR Lab members
  - name: Internal
    identifier: internal
    weight: 70

  - name: Contact
    url: /contact/
    parent: internal
    weight: 1

  - name: SharePoint Wiki
    url: https://bham.sharepoint.com/sites/LES-PSY-VRLab
    parent: internal
    weight: 2

  - name: Teams
    url: https://teams.microsoft.com/l/team/19%3AvhCl5BNPrgqEcGePBb_ZD8r9jXkHdzrtz_ZgcC85sL81%40thread.tacv2/conversations?groupId=6812d02e-2a15-47e0-a4cd-d1a042cbffcf&tenantId=b024cacf-dede-4241-a15c-3c97d553e9f3
    parent: internal
    weight: 3

  - name: Site Maintenance
    url: /site_maintenance/
    parent: internal
    weight: 4

  - name: CODA (outdated)
    url: https://tinyurl.com/CODAVRLab
    parent: internal
    weight: 5

  - name: CMS
    url: https://virtualrealitylab.netlify.app/admin
    parent: internal
    weight: 6
